spring:
  servlet:
    multipart:
      # 设置单个文件大小
      max-file-size: 50MB
      # 设置总上传的数据大小
      max-request-size: 100MB
  autoconfigure:
    exclude:
      # 禁用MongoDB数据库自动化配置
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration